/**
 *
 */
package com.forgedui.model.titanium;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.eclipse.ui.views.properties.IPropertyDescriptor;

import com.forgedui.model.property.IntegerPropertyDescriptor;
import com.forgedui.model.property.MinmaxValidator;
import com.forgedui.model.property.NumberCellEditor;
import com.forgedui.model.property.NumberPropertyDescriptor;
import com.forgedui.model.titanium.annotations.Unmapped;
import com.forgedui.util.Utils;

/**
 * @AutoGenerated
 */
public class ButtonBar extends TitaniumUIContainer {

	@Unmapped
	public static final String PROP_BUTTONS_COUNT = "buttons count";
	
	@Unmapped
	public static final String PROP_INDEX = "index";

	/**
	 * 
	 */
	@Unmapped
	private static final long serialVersionUID = 1L;

	private Integer index;

	private Integer style;

	public ButtonBar() {
		type = "Titanium.UI.ButtonBar";
	}

	@Override
	public void initDefaults() {
		super.initDefaults();
		setButtonsNumber(2);//init with 2 buttons by default
		setOpacity(0.0f);
	}
	
	@Override
	public List<? extends TabbedBarButton> getChildren() {
		return (List<? extends TabbedBarButton>) super.getChildren();
	}

	public void setButtonsNumber(int num){
		for (int i = children.size() - 1; i >= num; i--) {
			if(i > 0)
				((TabbedBarButton)children.get(i-1)).setLast(true);
			removeChild(children.get(i));
		}	
		for (int i = children.size(); children.size() < num; i++) {
			if(i > 0)
				((TabbedBarButton)children.get(i-1)).setLast(false);
			addChild(new TabbedBarButton(i==0,true,"Button"));
		}
	}
	
	public int getButtonsNumber(){
		return children.size();
	}

	@Override
	public IPropertyDescriptor[] getPropertyDescriptors() {
		List<IPropertyDescriptor> fullList = new ArrayList<IPropertyDescriptor>();
		fullList.addAll(Arrays.asList(super.getPropertyDescriptors()));
		NumberPropertyDescriptor npd = new NumberPropertyDescriptor(PROP_BUTTONS_COUNT, PROP_BUTTONS_COUNT,
				NumberCellEditor.INTEGER, false);
		npd.setValidator( new MinmaxValidator(1, 10));
		fullList.add(npd);

		IntegerPropertyDescriptor pd=null;
		for (IPropertyDescriptor iPropertyDescriptor : fullList) {
			if(PROP_INDEX.equals(iPropertyDescriptor.getDisplayName())){
				pd = (IntegerPropertyDescriptor)iPropertyDescriptor;
				break;
			}
		}
		fullList.remove(fullList.indexOf(pd));
		NumberPropertyDescriptor npd2 = new NumberPropertyDescriptor(pd.getId(), PROP_INDEX,NumberCellEditor.INTEGER, true);
		npd2.setValidator( new MinmaxValidator(0, getButtonsNumber()-1));
		fullList.add(npd2);

		return fullList.toArray(new IPropertyDescriptor[fullList.size()]);
	}
	
	@Override
	public Object getPropertyValue(Object propertyId) {
		if (PROP_BUTTONS_COUNT.equals(propertyId)){
			return "" + getButtonsNumber();
		}
		return super.getPropertyValue(propertyId);
	}
	
	@Override
	public void resetPropertyValue(Object id) {
		if (id instanceof Field && PROP_INDEX.equals(((Field)id).getName())){
			setIndex(0);
		} if (PROP_BUTTONS_COUNT.equals(id)){
			setPropertyValue(id, 2);
		} else {
			super.resetPropertyValue(id);
		}
	}
	
	@Override
	public void setPropertyValue(Object propertyId, Object value) {
		if (PROP_BUTTONS_COUNT.equals(propertyId)){
			setButtonsNumber((Integer) value);
			if(getIndex()>= getButtonsNumber())
				setIndex(getButtonsNumber()-1);
		} else if(propertyId instanceof Field && PROPERTY_OPACITY.equals(((Field)propertyId).getName())){
			super.setPropertyValue(propertyId, 0.0f);
		}else {
			super.setPropertyValue(propertyId, value);
		}
	}

	/**
	 * @param index the index to set
	 */
	public void setIndex(Integer index) {
		Integer oldValue = this.index;
		this.index = index;
		listeners.firePropertyChange(PROP_INDEX, oldValue, index);
		if (index == null){
			index = -1;
		}
		for (int i = 0; i < children.size(); i++) {
			((TabbedBarButton)children.get(i)).setSelected(i == index);
		}
	}

	/**
	 * @return the index
	 */
	public Integer getIndex() {
		return index;
	}

	/**
	 * @return the style
	 */
	public Integer getStyle() {
		return style;
	}

	/**
	 * @param style the style to set
	 */
	public void setStyle(Integer style) {
		this.style = style;
	}
	
	public void updateSelection(TabbedBarButton button){
		int index = getButtonIndex(button);
		if (Utils.getBoolean(button.getSelected(), false)){
			setIndex(index);
		} else {
			if (Utils.getInt(getIndex(), -1) == index){
				setIndex(null);
			}
		}
	}
	
	protected int getButtonIndex(TabbedBarButton button){
		for (int i = 0; i < children.size(); i++) {
			if (children.get(i) == button){
				return i;
			}
		}
		return -1;
	}
}