/**
 *
 */
package com.forgedui.model.titanium;

import com.forgedui.model.titanium.TitaniumUIElement.EnumType;
import com.forgedui.model.titanium.annotations.SupportedPlatform;
import com.forgedui.model.titanium.annotations.Unmapped;

/**
 * @AutoGenerated
 */
public class Switch extends TitaniumUIElement {
	
	@Unmapped
	public static final String PROPERTY_SWITCH_STYLE = "style";

	@Unmapped
	public static final String PROPERTY_SWITCH_VALUE = "value";
	
	@Unmapped
	public static final String PROPERTY_TITLE_ON = "titleOn";
	
	@Unmapped
	public static final String PROPERTY_TITLE_OFF = "titleOff";
	
	@Unmapped
	public static final String PROPERTY_TITLE = "title";
	
	/**
	 * 
	 */
	@Unmapped
	private static final long serialVersionUID = 1L;

	@SupportedPlatform(platforms = "android")
	private String titleOff;

	private Boolean enabled;

	@SupportedPlatform(platforms = "android")
	private String title;

	@SupportedPlatform(platforms = "android")
	private String titleOn;

	@SupportedPlatform(platforms = "android")
	private SwitchStyle style;

	private Boolean value=false;

	public Switch() {
		type = "Titanium.UI.Switch";
	}

	public Boolean getValue() {
		return value;
	}

	public void setValue(Boolean value) {
		Boolean oldValue = this.value;
		this.value = value;
		listeners.firePropertyChange(PROPERTY_SWITCH_VALUE, oldValue, value);
	}

	/**
	 * @return the titleOff
	 */
	public String getTitleOff() {
		return titleOff;
	}

	/**
	 * @param titleOff the titleOff to set
	 */
	public void setTitleOff(String titleOff) {
		String oldValue = this.titleOff;
		this.titleOff = titleOff;
		listeners.firePropertyChange(PROPERTY_TITLE_OFF, oldValue, titleOff);
	}

	/**
	 * @return the enabled
	 */
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * @param enabled the enabled to set
	 */
	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		String oldTitle = this.title;
		this.title = title;
		listeners.firePropertyChange(PROPERTY_TITLE, oldTitle, title);
	}

	/**
	 * @return the titleOn
	 */
	public String getTitleOn() {
		return titleOn;
	}

	/**
	 * @param titleOn the titleOn to set
	 */
	public void setTitleOn(String titleOn) {
		String oldValue = this.titleOn;
		this.titleOn = titleOn;
		listeners.firePropertyChange(PROPERTY_TITLE_ON, oldValue, titleOn);
	}

	/**
	 * @return the style
	 */
	public SwitchStyle getStyle() {
		return style;
	}

	/**
	 * @param style the style to set
	 */
	public void setStyle(SwitchStyle style) {
		SwitchStyle oldValue = this.style;
		this.style = style;
		listeners.firePropertyChange(PROPERTY_SWITCH_STYLE, oldValue, style);
	}
	
	public static enum SwitchStyle implements EnumType{
		SWITCH_STYLE_TOGGLEBUTTON,
		SWITCH_STYLE_CHECKBOX;
		
		public String getQDN() {
			return "Titanium.UI.Android." + super.toString();
		};
	}
}