/**
 *
 */
package com.forgedui.model.titanium;

import com.forgedui.model.Element;
import com.forgedui.model.titanium.annotations.Review;
import com.forgedui.model.titanium.annotations.Unmapped;

/**
 * @AutoGenerated
 */
public class TableViewSection extends TitaniumUIContainer {

	private static final long serialVersionUID = 1L;
	@Unmapped
	public static final String PROP_HEADER_VIEW = "TableViewSection.headerView";
	@Unmapped
	public static final String PROP_HEADER_TITLE = "TableViewSection.headerTitle";
	@Unmapped
	public static final String PROP_FOOTER_VIEW = "TableViewSection.footerView";
	@Unmapped
	public static final String PROP_FOOTER_TITLE = "TableViewSection.footerTitle";

	@Review(note = "What exactly?")
	private TitaniumUIBoundedElement headerView;

	private String footerTitle;

	// the (readonly) number of rows in the section - so ignore/hide this
	// property
	// private Integer rowCount;

	private String headerTitle;

	@Review(note = "What exactly")
	private TitaniumUIBoundedElement footerView;

	public TableViewSection() {
		type = "Titanium.UI.TableViewSection";
	}

	protected String getObjectName() {
		return "Titanium.UI.TableViewSection";
	}

	@Override
	public void setName(String name) {
		String oldName = getName();
		super.setName(name);
		if (oldName == null) {
			setHeaderTitle("Section");
		}
	}

	/**
	 * @return the headerView
	 */
	public TitaniumUIBoundedElement getHeaderView() {
		return headerView;
	}

	/**
	 * @param headerView
	 *            the headerView to set
	 */
	public void setHeaderView(TitaniumUIBoundedElement headerView) {
		Element oldElement = this.headerView;
		this.headerView = headerView;
		fireElementPropertySet(PROP_HEADER_VIEW, oldElement, headerView);
	}

	/**
	 * @return the footerTitle
	 */
	public String getFooterTitle() {
		return footerTitle;
	}

	/**
	 * @param footerTitle
	 *            the footerTitle to set
	 */
	public void setFooterTitle(String footerTitle) {
		String oldFooter = this.footerTitle;
		this.footerTitle = footerTitle;
		listeners.firePropertyChange(PROP_FOOTER_TITLE, oldFooter, footerTitle);
	}

	/**
	 * @return the headerTitle
	 */
	public String getHeaderTitle() {
		return headerTitle;
	}

	/**
	 * @param headerTitle
	 *            the headerTitle to set
	 */
	public void setHeaderTitle(String headerTitle) {
		String oldHeaderTitle = this.headerTitle;
		this.headerTitle = headerTitle;
		listeners.firePropertyChange(PROP_HEADER_TITLE, oldHeaderTitle, headerTitle);
	}

	/**
	 * @return the footerView
	 */
	public TitaniumUIBoundedElement getFooterView() {
		return footerView;
	}

	/**
	 * @param footerView
	 *            the footerView to set
	 */
	public void setFooterView(TitaniumUIBoundedElement footerView) {
		Element oldElement = this.footerView;
		this.footerView = footerView;
		fireElementPropertySet(PROP_FOOTER_VIEW, oldElement, footerView);
	}

	@Override
	public void removeChild(Element child) {
		if (child == headerView) {
			setHeaderView(null);
		} else if (child == footerView) {
			setFooterView(null);
		}
		super.removeChild(child);
	}

}