/**
 *
 */
package com.forgedui.model.titanium;

import com.forgedui.model.titanium.annotations.Review;
import com.forgedui.model.titanium.annotations.Unmapped;

/**
 * @AutoGenerated
 */
public class TextArea extends TitaniumUIElement {

	@Unmapped
	public static final String PRO_TOOLBAR = "Titanium.UI.TextArea.toolbar";
	
	@Unmapped
	public static final String VALUE = "Titanium.UI.TextArea.value";
 
	/**
	 * 
	 */
	@Unmapped
	private static final long serialVersionUID = 1L;

	private Float keyboardToolbarHeight;
	
	private KeyboardType keyboardType;

	private Boolean enabled;

	private String value = "Textarea";

	private String keyboardToolbarColor;

	private Boolean suppressReturn;

	private Boolean editable;

	@Review(note = "What the ")
	private TitaniumUIBaseElement[] keyboardToolbar;

	public TextArea() {
		type = "Titanium.UI.TextArea";
	}

	public TitaniumUIBaseElement[] getKeyboardToolbar() {
		return keyboardToolbar;
	}

	public void setKeyboardToolbar(TitaniumUIBaseElement[] keyboardToolbar) {
		this.keyboardToolbar = keyboardToolbar;
	}

	/**
	 * @return the keyboardToolbarHeight
	 */
	public Float getKeyboardToolbarHeight() {
		return keyboardToolbarHeight;
	}

	/**
	 * @param keyboardToolbarHeight the keyboardToolbarHeight to set
	 */
	public void setKeyboardToolbarHeight(Float keyboardToolbarHeight) {
		this.keyboardToolbarHeight = keyboardToolbarHeight;
	}

	public void setKeyboardType(KeyboardType keyboardType) {
		this.keyboardType = keyboardType;
	}

	public KeyboardType getKeyboardType() {
		return keyboardType;
	}

	/**
	 * @return the enabled
	 */
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * @param enabled the enabled to set
	 */
	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	 * @return the value
	 */
	public String getValue() {
		return value;
	}

	/**
	 * @param value the value to set
	 */
	public void setValue(String value) {
		String oldValue = this.value;
		this.value = value;
		listeners.firePropertyChange(VALUE, oldValue, value);
	}

	/**
	 * @return the keyboardToolbarColor
	 */
	public String getKeyboardToolbarColor() {
		return keyboardToolbarColor;
	}

	/**
	 * @param keyboardToolbarColor the keyboardToolbarColor to set
	 */
	public void setKeyboardToolbarColor(String keyboardToolbarColor) {
		this.keyboardToolbarColor = keyboardToolbarColor;
	}

	/**
	 * @return the suppressReturn
	 */
	public Boolean getSuppressReturn() {
		return suppressReturn;
	}

	/**
	 * @param suppressReturn the suppressReturn to set
	 */
	public void setSuppressReturn(Boolean suppressReturn) {
		this.suppressReturn = suppressReturn;
	}

	/**
	 * @return the editable
	 */
	public Boolean getEditable() {
		return editable;
	}

	/**
	 * @param editable the editable to set
	 */
	public void setEditable(Boolean editable) {
		this.editable = editable;
	}

}