/**
 *
 */
package com.forgedui.model.titanium;

import com.forgedui.model.titanium.annotations.Review;
import com.forgedui.model.titanium.annotations.Unmapped;

/**
 * @AutoGenerated
 * 
 *                TODO: Note sure about this Toolbar class should it implement
 *                Container or UI element
 */
public class Toolbar extends TitaniumUIContainer {

	@Unmapped
	private static final long serialVersionUID = 1L;
	
	public static final String ITEMS_PROP = "items";

	@Review
	private String[] items;

	public Toolbar() {
		type = "Titanium.UI.Toolbar";
	}

	public void setItems(String[] items) {
		String[] old = this.items;
		this.items = items;
		listeners.firePropertyChange(ITEMS_PROP, old, items);
	}

	public String[] getItems() {
		return items;
	}

}