/**
 *
 */
package com.forgedui.model.titanium;

/**
 * @AutoGenerated
 */
public class View extends TitaniumUIContainer {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public View() {

		type = "Titanium.UI.View";
	}

}