/**
 *
 */
package com.forgedui.model.titanium;

import com.forgedui.model.titanium.annotations.Unmapped;

/**
 * @AutoGenerated
 */
public class WebView extends TitaniumUIElement {

	@Unmapped
	private static final long serialVersionUID = 1L;
	
	@Unmapped
	private Object data;
	
	private String html;

	private String url;

	private Boolean scalesPageToFit;

	public WebView() {

		type = "Titanium.UI.WebView";
	}

	/**
	 * @return the html
	 */
	public String getHtml() {
		return html;
	}

	/**
	 * @param html the html to set
	 */
	public void setHtml(String html) {
		this.html = html;
	}

	/**
	 * @return the url
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * @param url the url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * @return the scalesPageToFit
	 */
	public Boolean getScalesPageToFit() {
		return scalesPageToFit;
	}

	/**
	 * @param scalesPageToFit the scalesPageToFit to set
	 */
	public void setScalesPageToFit(Boolean scalesPageToFit) {
		this.scalesPageToFit = scalesPageToFit;
	}

}