/**
 *
 */
package com.forgedui.model.titanium.iphone;

import com.forgedui.model.titanium.TitaniumUIElement;
import com.forgedui.model.titanium.annotations.SupportedPlatform;

/**
 * @AutoGenerated
 */
@SupportedPlatform(platforms="iphone")
public class NavigationGroup extends TitaniumUIElement {

	protected String getObjectName() {
		return "Titanium.UI.iPhone.NavigationGroup";
	}

}