/**
 *
 */
package com.forgedui.model.titanium.ios;

import com.forgedui.model.titanium.TitaniumUIElement;
import com.forgedui.model.titanium.annotations.SupportedPlatform;

/**
 * @AutoGenerated
 */
@SupportedPlatform(platforms = { "iphone", "ipad" })
public class AdView extends TitaniumUIElement {

	protected String getObjectName() {
		return "Titanium.UI.iOS.AdView";
	}

}